### ISSUE TITLE
When using the the example tcstring.nim, the following error is raised: c/path/to/futhark.nim(232, 28) Error: expression 'kind["value"].str' is of type 'string' and has to be used (or discarded)

### ISSUE THREAD

**Issue by MaheshE99ME25** [PMunch/futhark#112]

**Comment by PMunch** [comment]
Try upgrading your Nim version. There where some changes which made Futhark throw warnings, fixing those warnings was unfortunately not backwards compatible.

**Comment by MaheshE99ME25** [comment]
Upgraded from 2.0.4 to 2.0.8 and it worked. Thank you for the great module it really was helpful.

**Comment by PMunch** [comment]
Great to hear!
