### ISSUE TITLE
Hide aliased types

### ISSUE THREAD

**Issue by AmjadHD** [PMunch/futhark#120]
```c
typedef struct Point {
    int x;
    int y;
} Point;
```
translates to:
```nim
type
  struct_Point* = object
    x*: cint
    y*: cint
  Point* = struct_Point
```
`struct_Point` is exported, when arguably it shouldn't be.

**Comment by PMunch** [comment]
Futhark tries to emulate C, and in C when you import a module with a typedef'ed struct you get both the original and the typedef'ed version. So this works as intended.

Besides the output of `nim doc` suffers greatly if these aren't exported.

**Comment by AmjadHD** [comment]
These clutter the autocompletion suggestions, bloat the API and pollute the documentation.
What I had in mind is:
```nim
type
  Point* = object
    x*: cint
    y*: cint
```
and if there is a reference to `struct Point` replace it with the alias.

**Comment by PMunch** [comment]
C interoperability is still more important. And detecting `struct Point` across the entire output is harder than it sounds.
