### ISSUE TITLE
Question: type names.

### ISSUE THREAD

**Issue by Shinyzenith** [PMunch/futhark#25]
![image](https://user-images.githubusercontent.com/60808802/159076538-47916ab4-fbd7-42b1-950d-6cbb6dae140d.png)
sorry but why are type names so horrible  ༎ຶ‿༎ຶ

**Comment by PMunch** [comment]
Ah, those are intermediary names to allow you to redefine your own types in the mix. It's a bit complicated, but if you look around you should find something like

```nim
when not declared(structwllistener):
  type structwllistener = structwllistener_18485576
```

So you can use `structwllistener` without the numbers

**Comment by Shinyzenith** [comment]
Yep Rika over on the discord server told me the same. Thank you!
