### ISSUE TITLE
osx-Mojave nimble-install worked

### ISSUE THREAD

**Issue by Asc2011** [PMunch/futhark#28]
after localizing `libclang` via
`mdfind -name libclang.dylib`
 
the lib was found four at locations :

> /opt/local/libexec/llvm-13/lib/libclang.dylib
> /usr/local/Cellar/llvm/12.0.1/lib/libclang.dylib
> /usr/local/Cellar/llvm/10.0.1_1/lib/libclang.dylib
> /Library/Developer/CommandLineTools/usr/lib/libclang.dylib

i tried the first option, as it showed the highest version of LLVM.

`nimble install --passL:"-L/opt/local/libexec/llvm-13/lib" futhark`

showed no errors for Nim 1.6.4 ( installed via mac-ports )

**Comment by PMunch** [comment]
Great to hear that the instructions in the README works 👍
