### ISSUE TITLE
Opir generates json successfully, Futhark `key not found: pragmas [KeyError]`

### ISSUE THREAD

**Issue by arkanoid87** [PMunch/futhark#56]
I was trying to wrap https://github.com/max2344/pcsc-lite/blob/master/src/PCSC/pcsclite.h

```nim
  import futhark
  importc:
      path "/usr/include/PCSC"
      "pcsclite.h"
```
but
```
futhark.nim(464, 14) template/generic instantiation of `importcImpl` from here
nim-1.6.10/lib/pure/collections/tables.nim(234, 5) Error: unhandled exception: key not found: pragmas [KeyError]
```
so I've run Opir separately
```
$ opir -I/usr/include/PCSC/ ~/.cache/nim/pcsclite_d/futhark-includes.h | jq > pcsclite.h.json
```
and I've got a json without errors [pcsclite.h.json.txt](https://github.com/PMunch/futhark/files/10564247/pcsclite.h.json.txt)

after some elementary tracing, it happens on first execution of `createVar`, during parsing of `g_rgSCardRawPci`

relevant json section
```json
  {
    "kind": "var",
    "file": "/usr/include/PCSC/pcsclite.h",
    "position": {
      "column": 63,
      "line": 88
    },
    "name": "g_rgSCardRawPci",
    "linkage": "external",
    "type": {
      "kind": "alias",
      "value": "SCARD_IO_REQUEST"
    }
  },
```

relevant C section 
```C
extern const SCARD_IO_REQUEST g_rgSCardT0Pci, g_rgSCardT1Pci, g_rgSCardRawPci;
```

how does Futhark deals with extern declarations?

**Comment by PMunch** [comment]
What do you mean it happens in `stable` and not in `devel`? Futhark doesn't have a stable/devel version split. I will look into it, there was recently some changes made with pragmas.

**Comment by PMunch** [comment]
Are you on the latest (0.7.4) version? As of https://github.com/PMunch/futhark/commit/f568c8032eaed8c3e4c5972958feec8c8070705b there shouldn't be any access to "pragma" in the Futhark module.
