### ISSUE TITLE
What is `Futhark`'s license?

### ISSUE THREAD

**Issue by matkuki** [PMunch/futhark#72]
What is `Futhark`'s license and the license of it's generated code?
There is no license file in the repository.

**Comment by eclairevoyant** [comment]
Not to belabor the point too much, but generally MIT-licensed works (as well as BSD, ISC, zlib... ) should have an explicit license file including the copyright statement.

Per the license itself:

    Copyright <YEAR> <COPYRIGHT HOLDER>

and

    The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

But we can't really follow that if there's no notice to use.
Can an explicit file be created? (I am asking this as a packager.)
