### ISSUE TITLE
Failure to parse arrays of anonymous structs

### ISSUE THREAD

**Issue by averne** [PMunch/futhark#83]
futhark fails to parse/generate code for arrays of anonymous structs.

Originally discovered when attempting to import [`ffnvcodec/dynlink_loader.h`](https://github.com/FFmpeg/nv-codec-headers/).
![image](https://github.com/PMunch/futhark/assets/45773016/611f5fa1-47d2-4ad7-bcd4-3d8d696bf834)

Minimal repro:
```c
// test.h
// ----------------
struct Test {
    struct {
        int m;
    } a[10];
};
``` 
```nim
# test.nim
# ----------------
import futhark

importc:
    "test.h"
```

**Comment by averne** [comment]
Hi, thank you for the quick fix. I can confirm it now successfully parses both the minimal repro and the ffnvcodec header.

**Comment by PMunch** [comment]
Just pushed a new 0.10.0 version with the improved fix
