### ISSUE TITLE
Opir exited with non-zero exit code 127

### ISSUE THREAD

**Issue by general-rishkin** [PMunch/futhark#84]
I get this error:

> 
> 
> /home/grishkin/TestAtlasWorkspace/futhark/src/futhark.nim(717, 7) Hint: Running: opir -I/home/grishkin/TestAtlasWorkspace/graphlib -I/usr/lib/llvm-14/lib/clang/14.0.0/include /home/grishkin/.cache/nim/test0_d/futhark-includes.h [User]
> stack trace: (most recent call last)
> /home/grishkin/TestAtlasWorkspace/futhark/src/futhark.nim(726, 9) importcImpl
> /home/grishkin/TestAtlasWorkspace/graphlib/test0.nim(5, 1) template/generic instantiation of `importc` from here
> /home/grishkin/TestAtlasWorkspace/futhark/src/futhark.nim(661, 14) template/generic instantiation of `importcImpl` from here
> /home/grishkin/TestAtlasWorkspace/futhark/src/futhark.nim(726, 9) Error: Opir exited with non-zero exit code 127.
> Opir output: 
> /bin/sh: 1: opir: not found

The test file is very simle:

```
import futhark

importc:
    foo.h
```

FYI: I have an `atlas` workspace and a testproject beneath this.

**Comment by PMunch** [comment]
Well the error message is protty clear:
```
/bin/sh: 1: opir: not found
```
Opir simply can't be found. I assume Atlas maybe doesn't build packages it installs, or it places them somewhere not generally accessible.

**Comment by general-rishkin** [comment]
You are correct. This seems to be the case because I used nimble instead and it worked fine.
