### ISSUE TITLE
[bug] Futhark gets confused with Clang versions

### ISSUE THREAD

**Issue by heysokam** [PMunch/futhark#94]
I have clang17 installed, but futhark is searching for v16
```bash
$ build
opir: error while loading shared libraries: libclang.so.16: cannot open shared object file: No such file or directory

$ ls /usr/lib/libclang*
/usr/lib/libclang.so  /usr/lib/libclang-cpp.so  /usr/lib/libclang-cpp.so.17  /usr/lib/libclang.so.17  /usr/lib/libclang.so.17.0.6
```
I soft-fixed it by `ln -s` linking to the .so.16 version from the one I have, but I figured I should report it anyway.

System: ArchLinux
Nim Version: 2.0, compiled manually from the 2.0 branch (not on my path)

**Comment by PMunch** [comment]
Hmm, I just reinstalled Futhark and the error went away. Basically when `opir` is built it is linked to the version of Clang it finds. If your system then updates the version of Clang then this version no longer exists. Simply rebuilding Opir fixes the error.
