### ISSUE TITLE
Can't install futhark

### ISSUE THREAD

**Issue by remigijusj** [PMunch/futhark#99]
I am getting the following error when trying `nimble install futhark`. I have also attempted to link to clang directly, and install head version, same result:

```
Hint:  [Link]
/usr/bin/ld: /home/remi/.cache/nim/opir_r/@mopir.nim.c.o: in function `toNimType__opir_u191':
@mopir.nim.c:(.text+0x12f1): undefined reference to `clang_Type_getValueType'
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc   -o '/tmp/nimble_80717/githubcom_PMunchfuthark_#head/opir'
```
OS version: Ubuntu 20.04.2 LTS (on WSL2, 64bit)
Nim version: 2.0.2
Clang version: 10.0.0-4ubuntu1

**Comment by PMunch** [comment]
That's a very old version of Clang. Futhark hasn't been tried with anything lower than 15. Also you might need a separate libclang package.
